### PR TITLE
WIP: compile from Vulkan 1.2 vk.xml

### PR DESCRIPTION
**Pull request by sheaf**
I'm putting this together in a bit of a haphazard way, so I hope you'll forgive my mistakes. I'm eager to try some of the newer Vulkan features... for instance I just finished implementing shader debug printf debugging in [my `SPIR-V` compiler](https://gitlab.com/sheaf/fir), but I can't actually try it out until I update `vulkan-api`. I'd also love to try to mess around with ray tracing shaders.

With this patch, `genvulkan` manages to finish, but there are some problems when trying to compile the resulting code:

1. I'm getting the following import cycle:

```
Module imports form a cycle:
         module `Graphics.Vulkan.Types.Struct.SampleLocation'
        imports `Graphics.Vulkan.Types.Struct.Image'
  which imports `Graphics.Vulkan.Types.Struct.PhysicalDevice'
  which imports `Graphics.Vulkan.Types.Struct.Device'
  which imports `Graphics.Vulkan.Types.Struct.RenderPass'
  which imports `Graphics.Vulkan.Types.Struct.Attachment'
  which imports `Graphics.Vulkan.Types.Struct.SampleLocation'
```

It seems like this should be remedied by using a `{-# SOURCE #-}` import to break the loop. I don't know if there are any other import cycles.

2. `Graphics.Vulkan.Types.Struct.AabbPositionsNV` looks for `Graphics.Vulkan.Types.Struct.EnableBetaExtensions`, which is hidden under the `cabal` `enableBetaExtensions` flag, whereas `Graphics.Vulkan.Types.Struct.AabbPositionsNV` is not. I tried manually moving some modules into the `enableBetaExtensions` guarded part of the `cabal` file, but I couldn't get it to work.

3. When trying to compile with the flag `enableBetaExtensions`, I'm getting the following error in `Graphics.Vulkan.Types.Struct.EnableBetaExtensions`:

```
error: EnableBetaExtensions.hsc: In function 'main':
EnableBetaExtensions.hsc:721:5: error: attempt to take address of bit-field structure member 'instanceCustomIndex'
EnableBetaExtensions.hsc:726:5: error: attempt to take address of bit-field structure member 'mask'
EnableBetaExtensions.hsc:731:5: error: attempt to take address of bit-field structure member 'instanceShaderBindingTableRecordOffset'
EnableBetaExtensions.hsc:736:5: error: attempt to take address of bit-field structure member 'flags'
```

which is due to the following code:

```haskell
instance VulkanMarshal VkAccelerationStructureInstanceKHR where
    type StructRep VkAccelerationStructureInstanceKHR =
         'StructMeta "VkAccelerationStructureInstanceKHR" -- ' closing tick for hsc2hs
           VkAccelerationStructureInstanceKHR
           #{size VkAccelerationStructureInstanceKHR}
           #{alignment VkAccelerationStructureInstanceKHR}
           '[('FieldMeta "transform" VkTransformMatrixKHR 'False  -- ' closing tick for hsc2hs
                                                                 #{offset VkAccelerationStructureInstanceKHR, transform}
                1
                'True -- ' closing tick for hsc2hs
                'True), -- ' closing tick for hsc2hs
             ('FieldMeta "instanceCustomIndex" Word32 'False 
                                                             #{offset VkAccelerationStructureInstanceKHR, instanceCustomIndex}
                1
                'True -- ' closing tick for hsc2hs
                'True), -- ' closing tick for hsc2hs
             ('FieldMeta "mask" Word32 'False 
                                              #{offset VkAccelerationStructureInstanceKHR, mask}
                1
                'True -- ' closing tick for hsc2hs
                'True), -- ' closing tick for hsc2hs
             ('FieldMeta "instanceShaderBindingTableRecordOffset" Word32 'False
                #{offset VkAccelerationStructureInstanceKHR, instanceShaderBindingTableRecordOffset}
                1
                'True -- ' closing tick for hsc2hs
                'True), -- ' closing tick for hsc2hs
             ('FieldMeta "flags" VkGeometryInstanceFlagsKHR 'True 
                                                                  #{offset VkAccelerationStructureInstanceKHR, flags}
                1
                'True -- ' closing tick for hsc2hs
                'True), -- ' closing tick for hsc2hs
             ('FieldMeta "accelerationStructureReference" Word64 'False
                #{offset VkAccelerationStructureInstanceKHR, accelerationStructureReference}
                1
                'True -- ' closing tick for hsc2hs
                'True)] -- ' closing tick for hsc2hs
           'False -- ' closing tick for hsc2hs
           'False -- ' closing tick for hsc2hs
           '[] -- ' closing tick for hsc2hs
```

### CODE REVIEW

**Comment by sheaf** [comment]
Issue 3 is due to VkAccelerationStructureInstanceKHR using bitfields as explained in the XML:

```
        <type category="struct" name="VkAccelerationStructureInstanceKHR">
            <comment>The bitfields in this structure are non-normative since bitfield ordering is implementation-defined in C. The specification defines the normative layout.</comment>
            <member><type>VkTransformMatrixKHR</type>                                    <name>transform</name></member>
            <member><type>uint32_t</type>                                                <name>instanceCustomIndex</name>:24</member>
            <member><type>uint32_t</type>                                                <name>mask</name>:8</member>
            <member><type>uint32_t</type>                                                <name>instanceShaderBindingTableRecordOffset</name>:24</member>
            <member optional="true"><type>VkGeometryInstanceFlagsKHR</type>              <name>flags</name>:8</member>
            <member><type>uint64_t</type>                                                <name>accelerationStructureReference</name></member>
        </type>
````

This means we need to adjust `genStructField` to pass the offsets, and adjust the internal `Vulkan.Marshal` machinery to support bitfields. It seems like a lot of work, as currently `readField`/`writeField` use `peekByteOff`/`pokeByteOff` whereas we would need to perform masking:

```haskell
readBitField @name mask ptr = ( mask .&. ) <$> readField @name ptr
writeBitField @name mask ptr = do
  v <- readBitField @name (complement mask) ptr
  writeField @name ((mask .&. x) .|. v) ptr
```

This is the only struct that uses bitfields in the whole `vk.xml` file at the moment, so it is quite a hassle to have to do all this for this single use case.

**Comment by sheaf** [comment]
OK, I've added support for bitfields in `Vulkan.Marshal.Internal`, let me know what you think. Next I will try to update `genvulkan` to emit the correct `FieldMeta`

**Comment by sheaf** [comment]
I'm thinking about how to specify the offsets, given that we can't use `hsc2hs` for this. So we have:

```c
struct VkAccelarationStructInstanceKHR {
   VkTransformMatrixKHR transform;
   uint32_t instanceCustomIndex : 24;
   uint32_t mask : 8;
   uint32_t instanceShaderBindingTableRecordOffset : 24;
   VkGeometryInstanceFlagsKHR flags : 8;
   uint64_t accelerationStructureReference;
}
```

I need to produce the following `FieldMeta`s:

```haskell
[ FieldMeta "transform"                              VkTransformMatrixKHR       False  0 1 True True NoBitmask
, FieldMeta "instanceCustomIndex"                    Word32                     False 48 1 True True (Bitmask 0x00ffffff)
, FieldMeta "mask"                                   Word32                     False 48 1 True True (Bitmask 0xff000000)
, FieldMeta "instanceShaderBindingTableRecordOffset" Word32                     False 52 1 True True (Bitmask 0x00ffffff)
, FieldMeta "flags"                                  VkGeometryInstanceFlagsKHR False 52 1 True True (Bitmask 0xff000000)
, FieldMeta "accelerationStructureReference"         Word64                     False 56 1 True True NoBitmask
]
```

but I can't ask `hsc2hs` to give me those offsets (as it refuses to deal with bitfields), so we need to compute them ourselves (using e.g. offsets and sizes of previous fields). So we'll have to change `genStructField` to keep track of this data, and adjust the traversal that uses `genStructField` in consequence. It seems manageable, I'll give it a try. I suppose it's OK if it's a bit rickety, as really it only needs to be able to handle this single situation.

**Comment by achirkin** [comment]
Sorry I don't participate in this discussion a lot and thanks for all the work on this PR!
Your suggestions seem very reasonable to me. Such an unfortunate situation with these bit fields. Would the byte ordering be an issue here in theory?

**Comment by sheaf** [comment]
No, `vk.xml` says the ordering is as defined in the `XML` file, and if the compiler chooses to order things differently that's an error.

```xml
<comment>The bitfields in this structure are non-normative since bitfield ordering is implementation-defined in C. The specification defines the normative layout.</comment>
```

[The specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureInstanceKHR.html) says the following:

> The C language spec does not define the ordering of bit-fields, but in practice, this struct produces the correct layout with existing compilers. The intended bit pattern is for the following:
> 
>   instanceCustomIndex and mask occupy the same memory as if a single int32_t was specified in their place
>       - instanceCustomIndex occupies the 24 least significant bits of that memory
>       - mask occupies the 8 most significant bits of that memory
> 
>   instanceShaderBindingTableRecordOffset and flags occupy the same memory as if a single int32_t was specified in their place
>       - instanceShaderBindingTableRecordOffset occupies the 24 least significant bits of that memory
>       - flags occupies the 8 most significant bits of that memory
> 
> If a compiler produces code that diverges from that pattern, applications must employ another method to set values according to the correct bit pattern.

**Comment by achirkin** [comment]
Ugh, sorry, I did something stupid to the repo and the pull request was closed automatically and does not want to reopen. Could you please open another one?

**Comment by achirkin** [comment]
In the end, I did not modify fieldmeta to include bitmasks, but modified this structure alone manually (since we need another way to parse bitfields anyway) combining bitfields as instanceCustomIndexAndMask and  instanceShaderBindingTableRecordOffsetAndFlags. This would be a todo for the next release...

**Pull request closed without merging**
