### PR TITLE
vulkan-triangles: Implemented Uniform buffers part from vulkan-tutorial.com

### PR DESCRIPTION
**Pull request by cjay**
It rotates with perspective :)

### CODE REVIEW

**Comment by achirkin** [comment]
Wow, cool!

One thing first: as a developer of these bindings and the [`easytensor`](https://github.com/achirkin/easytensor) library, I shamelessly lobby the latter here :)
Could you please switch from `linear` to `easytensor` to not use two different vector libraries in one example program? The [`Lib.Vulkan.Vertex`](https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib/Vulkan/Vertex.hs) module shows an example of usage; you still get [matrix helpers](http://hackage.haskell.org/package/easytensor-1.0.1.0/docs/Numeric-Matrix-Class.html); and as a small bonus, you don't need to manually write `Storable` instances for your structs.

**Comment by achirkin** [comment]
Ah, you probably used an older `easytensor` library and faced helpers "not implemented" problem. Thanks to @Rotaerk , this was implemented in the newer version https://github.com/achirkin/easytensor/pull/10

**Comment by cjay** [comment]
Oh, yes I had an older version, and in the readme of easytensor "Implementation of the class" under "Homogenous coordinate operations" has no check mark. I will try with the new version.

It's awesome that PrimBytes can be derived for structs that easily. Does it obey the alignment requirements for UBOs mentioned [here](https://vulkan-tutorial.com/Uniform_buffers/Descriptor_pool_and_sets#page_Alignment_requirements)? It's unfortunate that C structs and GPU structs (whatever the correct term is) have different alignment requirements, maybe a newtype wrapper that causes different PrimBytes implementations is needed.

By the way, I'm planning to try to make a little 2D engine after I finish the tutorial. I'm curious to see how much synergy there is between Haskell and Vulkan regarding multi-threading. Do you currently have plans or ideas for a higher level library on top of vulkan-api? I might end up writing some abstractions that could contribute to such a lib.

**Comment by achirkin** [comment]
Hmm, by default alignment for structs in `PrimBytes` is derived as a maximum of its elements alignment, but  `DataFrame`s have the same alignment as the alignment of their elements. So, you would have to redefine it. Theoretically, you can just manually override `byteAlign` for your struct in the instance declaration, but I am not sure how the rest of `GPrimBytes` functions will behave with it.
I think, a reasonable long-term solution would be to make change the default alignment for  all `DataFrame`s: `N` for scalars, `2N` for 2D vectors, and `4N` for the rest.
In this program, you structure is nicely packed, so you only need to make sure that the buffer (or underlying `ByteArray#`) is 16bytes-aligned. 

I don't plan to write a really high-level vulkan-based graphics library, but I have some plans for greatly simplifying current bindings api: put error codes into exceptions where appropriate, leverage some obvious pointer boilerplate, etc.

**Comment by achirkin** [comment]
From how the code `easytensor` appears to me now, you should be able to just add `byteAlign` and `byteSize` to an otherwise empty `instance PrimBytes UniformBufferObject where` to change alignment and (array element) padding of your data type. All the array write / read functions and DataFrame/Storable should pick up these values.
I had some doubts if `GPrimBytes` implementation would acknowledge this partial overriding of `PrimBytes`, but it looks ok. Still, if you face some alignment issues, first look into this direction.

**Comment by achirkin** [comment]
Good, thanks! One last thing: could you please move parts of code specific to your uniform object (`UniformBufferObject`, `updateUB`, ..?) to some other module, similar to `Lib.Vulkan.Vertex`? And maybe rename it somehow that people who see this example program don't think it is part of Vulkan API?

**Comment by Rotaerk** [comment]
FYI, I've implemented the final result of vulkan-tutorial.com here: https://github.com/Rotaerk/vulkanTest/blob/master/vulkan-tutorial/main/src/Main.hs.

**Comment by achirkin** [comment]
@Rotaerk wow, 2262 lines! How that compares to C version?
Great to see that everything works! Have you investigated why loading the model takes a while, and the RAM footprint during the loading is more than a GB?

ps: I think it would be nice to have a list of current projects on github that use this library. That would help me to test vulkan-api changes against use-cases, and it would help newcomers to to learn the api by example.

**Comment by Rotaerk** [comment]
Nah, I haven't done much digging beyond getting it working.  I'm leaving that vulkan-tutorial implementation alone going forward, and now I'm playing around, making my own stuff, in https://github.com/Rotaerk/vulkanTest/tree/master/sandbox.  I implemented a KTX file parser so that I can start implementing the examples here: https://github.com/SaschaWillems/Vulkan (since his assets are mostly KTX files).  Still working on getting everything wired up to load and render a KTX texture.

**Comment by cjay** [comment]
Refactoring done.

**Comment by achirkin** [comment]
Great, thanks!

**Pull request merged**
