### PR TITLE
Rest of tutorial

### PR DESCRIPTION
**Pull request by cjay**
I implemented multiple frames in flight, fences and small other stuff from the tutorial that came before the Uniform Buffers chapter but was missing.

I also tried to make the recreation of descriptor- and uniform-buffer-related things depend on if the swap chain length has changed after recreation (not sure if this can actually happen, I think in theory it is allowed). What the tutorial does with these things, is create them only once and just assume that the array sizes are still appropriate after swap chain recreation. It should probably at least exit with an error if that assumption turns out to be wrong ([reported bug](https://github.com/Overv/VulkanTutorial/issues/129)).

Unfortunately the on demand creation (see `redoOnDemand`) clashes with the use of `locally` in `redoOnOutdate`. The resource handles get stored in the IORef and stay accessible, but due to `locally` they get deallocated too soon and are stale in the next iteration. What I need to happen is that the deallocations get bound to the scope outside of `redoOnOutdate`, but I can't move the allocation out of this scope because of the dependence on the new swap chain length. I wish I could somehow capture the recorded deallocation calls and pass them out of the scope to run them outside.

I need your opinion here. Have I hit a hard limitatiton of continuation-based resource management? Do you know a way around this? I can only imagine ugly workarounds for this problem, but not a satisfying solution. I'm also not sure if this problem actually matters for programs that do something useful. I guess games rarely have to go through swap chain recreation.

### CODE REVIEW

**Comment by achirkin** [comment]
While I don't have a pc at hand to look into your code, my first suggestion would be factor swapchain recreation out of the scope of `locally` and break the execution of stuff inside `locally` whenever you face the swapchain-needs-to-be-recreated exception. The whole idea of this approach is precisely to force such use (but I haven't had a lot of vulkan programming experience at the time of writing that so I am not totally sure if this is always a good idea). 

Maybe the better solution would be to add a primitive to the monad, such that would allow to create a placeholder for a resource and then initialize and re-initialize it multiple times. But I am not sure how much this is justified right now.

**Comment by cjay** [comment]
The swapchain re-creation is fixed now, taking advantage of having the same length on the new swapchain works, and now the old swapchain gets passed when creating a new one. I had to make the swapchain creation and destruction manual and keep it in a mutable variable. This is somewhat similar to your idea of having a placeholder for the resource.

In other news, texture mapping is implemented now. Also, I recommend `git diff -b` for the latest commit, the normal diff is blown up by indentation changes.

However, there is still one thing that should be changed. Currently there is a wait when recreating the swapchain that needs to happen for the deallocations to be successful. It would be better to defer the wait together with the deallocations, while continuing pipeline setup and draw calls with the new swapchain. Once again I wish I could somehow capture the recorded deallocation calls to be able defer them. I'm pretty sure it's impossible to capture them directly, so I think the way forward would be using coroutines or threads. Suspending execution of a thread should allow to defer deallocations nicely.

I now expect that this resource management challenge will occur with other things too. When asking on the #vulkan irc channel on how people handle swapchain recreation, two people mentioned that they have lists for deferred destruction of various things, with the destructions happening after a certain frame is finished, signaled by a fence. So it seems that in more complex Vulkan programs there is a need to put every frame in a coroutine or thread anyway, to defer those destructions.

**Comment by achirkin** [comment]
Hmm, this is definitely a food for thought. Maybe we can keep two swapchains allocated in mutable variables and swap them too? :) So that we can call the code to cleanup the bad swapchain after the new one is initialized. And in general with such approach, rather than rendering each frame in a separate thread, maybe one could keep a single thread for deferred deallocations of some critical resources (like swapchains)?

**Comment by cjay** [comment]
I finally have designed a solution, this was an interesting problem. The new `asyncRedo` function allows to  restart a block while the previous run is not yet finished, this enables deferred deallocation. There is now a wait for the frame fences before any deallocation happens. This function works even without `-threaded` despite using `forkIO` internally by using `yield` at the right time.

After discovering that `glfwMainLoop` stops working when `-threaded` is on, I found out that all GLFW event processing functions have to run in the main thread. So now the main thread is dedicated for GLFW event processing only, and a separate thread is now spawned for rendering. This also has other advantages, now the window contents get redrawn on macOS while resizing the window. Unfortunately because of this change, `-threaded` is now required. However I'm pretty sure this is the right way to do the event processing. Without having a thread that accept events all the time, stalls in event processing are hard to avoid.

In other news, depth buffering and loading the house model from the tutorial is also implemented.

I consider my `asyncRedo` experimental, it probably shouldn't be in the example project for now, since an example project should showcase best practices. Despite my success I have no idea if it's actually a good idea :)
Maybe a completely different approach to resource management that doesn't use continuations is better?

I think I'll finish the last two sections of the tutorial now, and after that make a commit that removes `asyncRedo` and simply recreates everything that depends on the swapchain when the swapchain changes, so that you can merge the whole thing. This is also what the author of the tutorial chose to do after my bugreport, he didn't optimize for the case when the new swapchain length stays the same. After that I'll make a permanent fork of vulkan-triangles and try to make an actual engine and see if `asyncRedo` is flexible enough.

**Comment by achirkin** [comment]
Great job! Thanks, I would like to play with both versions (with/out `asyncRedo`) for educational purposes.
I also have doubts that the continuation monad is the best way to handle resources, so maybe you would want to switch to something more canonical in your next project :) But if you have such an option, try to keep both versions in your next program; it would be super interesting to compare the two approaches!

Regarding the `-threaded` options - this is totally fine. This is a long standing problem for many haskell-C bindings (such as GLFW and OpenGL) - having to keep all calls to these bindings in the main capability of a threaded Haskell runtime. One of the greatest advantages of Vulkan is that you can call it freely from any and many threads; thus, at some point, you would anyway need to switch to `-threaded`.

**Comment by cjay** [comment]
Last part of tutorial is implemented. I can now make the simplification commit. Do you want both versions with and without asyncRedo in the repo? I'm not sure what is the best way to do this. Multiple branches?

**Comment by achirkin** [comment]
Cool! If it's ok, just make the simplification changes in one last commit. I will go through all changes in a few week; want to try the tutorial too :)

**Comment by cjay** [comment]
Done :)

**Comment by cjay** [comment]
Btw I started my fork of vulkan-triangles [here](https://github.com/cjay/vulkan-engine).

**Comment by cjay** [comment]
I discovered a dangerous mistake of mine, see last commit. The `withArrayLen` I wrote should probably be in `Graphics.Vulkan.Marshal`, make sure I did it correctly though :). Maybe the `Storable` instance of Vulkan structs shouldn't be exposed directly to prevent such mistakes?

**Comment by achirkin** [comment]
Still catching up with lots of code, so I decided to rebase here my latest commits from master.

**Comment by cjay** [comment]
I'm a bit confused by the rebase and force-push. It looks like you managed to make small changes to the original commits while rebasing? It's weird that github pretends the original commits never existed. IIRC the one time I tried force-push myself it showed more info, but I can't find it any more.

Nice work on the `bFieldOffsetOf`. By the way, can we get rid of the `2` in the type signature of `vertIADs` without resorting to `fromList`? That source of errors already bit me when I reduced the number of elements in my fork from 3 to 2 and forgot to update the type signature, which lead to random data being read.

I wish I were able to understand the type-level programming involved with idiomatic use of easytensor. Do you have some recommendations for me what to read? Should I get Isovector's book? I hope I don't need to read the whole book before understanding that stuff though. Maybe it should be called hardtensor ;)

In case you want to reactivate `asyncRedo`, my fork contains fixes that aren't in the history of this repository: [Program.hs](https://github.com/cjay/vulkan-engine/blob/master/src/Lib/Program.hs#L430)

**Comment by achirkin** [comment]
Yeah, I am really sorry, I should have done it via normal  merge. I did not expected I could push to your fork at all! But then it was done, and I did not know how to revert it :)

Do you mean you forgot to change the size of `verIADs` in signature from `2` to `3`, but wrote to it outside of the index using `ST.writeDataFrame` and there were no explicit error about index out of bounds? That would be a bug! The type signature should be an aid rather than a burden. But if it does not fit the case, you can always wrap a `DataFrame t ds` into a `SomeDataFrame t` to hide the dimensionality completely, or into an `XFrame` to hide some of the dimensions.

Regarding "idiomatic" easytensor -- don't know how to do it yet either. Just exploring. At this moment this just means minimizing the number of ugly `fromJust`s :) These days I am trying to figure out good ways to use `easytensor` without a lot of pain but with the provided safety. It does not go very smooth, so I perfectly understand your concerns. I plan to write a detailed tutorial on `dimensions` and `easytensor` next weekend on ZuriHac, or by the end of the month at latest.

Thanks for the `asyncRedo`, I will definitely look into that when finish learning the tutorial and your PR!

**Comment by achirkin** [comment]
Do you mind if I continue with small commits here before I merge the PR?

**Comment by cjay** [comment]
No problem, you can continue to commit.

I had `3` entries in `vertIADs` (position, color and texture coordinate), and then removed the color entry, but forgot to change the type signature back to `2`. I think this resulted in the third field having undefined contents, or maybe zeros.
The number from the type signature is used in `createGraphicsPipeline`, where `vertIADs` is passed as `attrDescs`:

        &* set @"vertexAttributeDescriptionCount"
          (fromIntegral . totalDim $ dims `inSpaceOf` attrDescs)
        &* setDFRef @"pVertexAttributeDescriptions" attrDescs

That way, the invalid third field was actually read by `vkCreateGraphicsPipelines`. Luckily one of the validation layers complained. I don't remember what it said, probably it was a duplicate binding or location number.

Looking forward to your `easytensor` tutorial. By the way, will you be at monadic.party too? I'll be there.

**Comment by achirkin** [comment]
Ah, I see. The unwritten part was probably random bytes, because GHC does not zero `ByteArray`s upon creation (at least in recent versions). I think, using a `fromList` is the most viable alternative here right now.
There is also a mighty function `packDF`, but its type-family signature is very hard to infer for GHC. It will definitely complain at compile time if you change the number of arguments, but you won't like the error message ;)

Oh, and by the way, very important change in easytensor in the new version! It's 0-based indexing now, rather than 1-based. Sorry for that, but I had a lot of reasons for this change.

No, unfortunately I am not coming to monadic.party , need to stay in Zurich for a while.

**Pull request merged**
