### PR TITLE
Fixed vulkan-triangles, updated README and deps for macOS

### PR DESCRIPTION
**Pull request by cjay**

### CODE REVIEW

**Comment by cjay** [comment]
@o1lo01ol1o Can we get rid of DYLD_LIBRARY_PATH in default-darwin.nix? See the changes to README-macOS.md and [this](https://gitlab.haskell.org/ghc/ghc/issues/11617).

**Comment by TravisWhitaker** [comment]
@achirkin @o1lo01ol1o Anything else required to merge this?

**Comment by achirkin** [comment]
Ugh, sorry @cjay , I somewhat though this is a work-in-progress PR. I don't use nix, so I cannot review this meaningfully, but I am happy to merge this if our nix colleagues agree.

**Comment by achirkin** [comment]
Sorry, I don't know why I did not do this before :)

**Pull request merged**
